export interface RaftSummaryItem {
  id: number;
  name: string;
  area_m2: number;
  perimeter_m: number;
  length_m: number;
  width_m: number;
  angle_deg: number;
  solarPanelCount?: number;
  focusFactor: number;
  cableCount: number;
  shoreAnchors: number;
  bedAnchors: number;
  selectedCable: string;
  waterDepth_m: number;
  bedAnchorDist_m: number;
  shoreAnchorDist_m: number;
  /**
   * Per-raft Broms pile overrides. Omit to keep the project-default pile
   * (shore D0.45/L6.5, bed D0.35/L8.0 — sized for the small/medium rafts).
   * The large rafts (higher line tension) need a bigger pile so BP-1..BP-5
   * clear their utilization <= 1.0 threshold; see .agentsroom memory
   * `features/mooring-calculation` for the Broms formula this feeds.
   */
  shorePileD_m?: number;
  shorePileL_m?: number;
  bedPileD_m?: number;
  bedPileL_m?: number;
  /** Bars on the tension face of the shore / lake-bed pile (one layer) and their diameter, mm. */
  shoreRebarFaceCount?: number;
  shoreRebarDia_mm?: number;
  bedRebarFaceCount?: number;
  bedRebarDia_mm?: number;
  /** ROUND shore pile: total bars of the cage, equally spaced on a circle. */
  shoreRebarCount?: number;
  /** Design strength of this raft's pile bars Rs, MPa (omit for the project value). */
  pileRebarRs_MPa?: number;
  /** Piles per shore / lake-bed anchor point (omit for 1). BÈ 5 uses twin piles. */
  shorePilesPerPoint?: number;
  bedPilesPerPoint?: number;
}

export interface MooringCoordinate {
  raft: string;
  code: string;
  type: 'SHORE' | 'BED';
  xRaft: number;
  yRaft: number;
  xAnchor: number;
  yAnchor: number;
  zAnchor: number;
  span: number;
  azimuth: number;

  /** Lake-bed lines: id of the base the line is tied to. Two facing lines of two rafts may share one base (same id, same position). */
  anchorId?: string;
  /** Code of the line of the facing raft tied to the same base. */
  sharedWith?: string;
  /** Shore line that was a lake-bed line, turned into a bored pile by the owner's rule of 2026-10-08 (design output, not a staked pile). */
  converted?: boolean;
}

/**
 * The 9 raft clusters of Hồ Huổi Vanh — plan of 2026-10-08 (BÈ 1, 2, 3, 3A, 5A,
 * 6, 7, 8, 9; 95.873 m²; 18.354 panels). 3A = old 4 + 5, 5A = old 6 + 7,
 * 6 = old 8, 7 = old 9, 8 = old 10 + 11, 9 = old 12.
 *
 * The rows live in huoiVanhRaftCatalogue.json, which is GENERATED by
 * `npx vite-node scripts/buildRaftCatalogue.ts` from the raft outlines, the
 * line file and the calculation engine — never edit it by hand. The rules
 * (bounding rectangle, panel share, focus factor, cable, shore pile, lake-bed
 * pile) are documented at the top of that script.
 *
 *  - Shore anchors: round bored piles D350 cast in place, the cable shackled
 *    0.1 m above the ground (anchor.shoreArm_e_m). BÈ 3A and BÈ 5A need TWIN
 *    piles; BÈ 8 needs CB500-V bars and L = 7.5 m.
 *  - Lake-bed anchors: by default an RC base held by 4 screw piles
 *    (anchor.bedAnchorOption = 'PA3_SCREW_BASE', see screwAnchorBed.ts). The
 *    lake-bed PILE columns (bedPile*, bedRebar*) are the alternative PA1 design.
 *  - focusFactor of the three merged rafts is an ASSUMPTION (the larger
 *    focus × N of the two parent rafts): no force-distribution model exists
 *    for the merged shapes.
 */
import raftCatalogue from './huoiVanhRaftCatalogue.json';

export const HUOI_VANH_RAFTS: RaftSummaryItem[] = raftCatalogue as RaftSummaryItem[];

export const HUOI_VANH_DEFAULT_PROJECT = {
  id: 'huoi-vanh-fpv',
  name: 'Dự án Điện Mặt Trời Nổi Hồ Huổi Vanh',
  code: 'HV-FPV-2026',
  location: 'Hồ Huổi Vanh, Tỉnh Điện Biên',
  designer: 'Kỹ sư Kết cấu Thủy công & Năng lượng tái tạo',
  date: '2026-08-19',
  note: 'Tính toán hệ thống neo 9 cụm bè pin nổi (BÈ 1, 2, 3, 3A, 5A, 6, 7, 8, 9; tổng 95.873 m², 18.354 tấm pin), 295 tuyến cáp neo Polyester PES-28/32/40/48: 231 điểm neo bờ bằng cọc khoan nhồi D350 và 32 đế BTCT + 4 vít xoắn dưới đáy hồ, đặt giữa hai bè (cả 32 đế dùng chung cho hai bè đối diện); 9/9 bè đạt C9 (P/N ≤ 15 m).',
  systemType: 'solar_fpv' as const,
  activeRaftId: 1,
  meta: {
    name: 'Dự án Điện Mặt Trời Nổi Hồ Huổi Vanh',
    code: 'HV-FPV-2026',
    location: 'Hồ Huổi Vanh, Tỉnh Điện Biên',
    designer: 'Kỹ sư Kết cấu Thủy công',
    date: '2026-08-19',
    note: 'Hồ chứa nước Huổi Vanh — Hệ neo 9 bè pin mặt trời nổi (neo bờ cọc khoan nhồi D350, neo đáy đế BTCT + vít xoắn)'
  },
  raft: {
    length_m: 90.0,
    width_m: 41.0,
    draft_m: 0.2,
    freeboardHeight_m: 0.35,
    displacement_t: 120.0,
    solarPanelCount: 790,
    solarPanelArea_m2: 2.701,
    // TCVN 2737:2023 design basis: panel tilt 12.0°, C_d = 1.15.
    solarTilt_deg: 12.0,
    solarShieldFactor: 0.55,
    cdPanel: 1.15,
    cdFloat: 1.1,
    windAreaOverride_m2: 0,
    currentAreaOverride_m2: 0,
    southDist_m: 17.1,
    northDist_m: 33.2,
    eastDist_m: 44.2,
    westDist_m: 27.0
  },
  env: {
    mndbt_m: 383.0,
    mncn_m: 384.0,
    maxDepth_m: 6.2,
    minWaterDepthUnderRaft_m: 1.5,
    bankSlope_m: 3.1,
    waterDepth_m: 6.0,
    tideRange_m: 1.0,
    windSpeed_ms: 20.0,
    windCd: 1.3,
    currentSpeed_ms: 0.5,
    currentCd: 1.2,
    waveHs_m: 0.2,
    waveTp_s: 2.0,
    waveCd: 1.0,
    waveCurrentFactor: 1.05,
    combinationFactor: 1.0,
    airDensity: 1.25,
    waterDensity: 1000.0,
    gravity: 9.81
  },
  line: {
    count: 20,
    longSideCount: 6,
    shortSideCount: 4,
    shoreLineCount: 16,
    bedLineCount: 4,
    effectiveCount: 6,
    horizontalAngle_deg: 30.0,
    type: 'cable' as const,
    cableCode: 'PES-28',
    chainDiameter_mm: 28,
    chainGrade: 'U2' as const,
    mbl_kN: 235.0,
    unitWeightAir_kgpm: 0.54,
    pretension_kN: 5.0,
    focusFactor: 0.276,
    totalLength_m: 35.0,
    groundedLengthMin_m: 5.0,
    seabedFrictionCoef: 0.8
  },
  anchor: {
    mode: 'pile' as const,
    // Lake-bed anchors: RC base + 4 screw piles (owner's workbook of 2026-10-08).
    bedAnchorOption: 'PA3_SCREW_BASE' as const,
    pileBedType: 'method1' as const,
    soilShore: 'clay' as const,
    soilBed: 'mud' as const,
    soil: 'mud' as const,
    // Client requirement: every pile is a SQUARE reinforced-concrete pile
    // (cọc vuông BTCT); shoreD_m / bed1D_m are the side of the square.
    // Shore piles: ROUND bored piles D350 cast in place (owner's decision,
    // 2026-10-04 — a small rig works on the steep bank without vibration).
    // Lake-bed piles: square precast 350 x 350, driven from a barge.
    shorePileShape: 'circular' as const,
    shoreRebarCount: 6,
    bedPileShape: 'square' as const,
    cuShore_kPa: 40.0,
    cuBed_kPa: 20.0,
    sfPile: 2.5,
    sfUplift: 2.0,
    concreteRb_MPa: 14.5,
    // Pile bending per TCVN 5574:2018: bars on the tension face, design strength
    // Rs (CB400-V), a_s = 50 mm, and a load factor of 1.2 on the wind-governed moment.
    concreteRbt_MPa: 1.05,
    pileRebarRs_MPa: 350,
    pileRebarCover_mm: 50,
    pileBendingLoadFactor: 1.2,
    // Every pile has 4 corner bars (owner's instruction): 2 bars on the tension face.
    shoreRebarFaceCount: 2,
    shoreRebarDia_mm: 25,
    bedRebarFaceCount: 2,
    bedRebarDia_mm: 25,
    // The shore cable is shackled at the pile neck, 0.1 m above the ground.
    // This is a CONSTRUCTION REQUIREMENT of the 4-bar design: a higher
    // attachment point raises the bending moment (it was 0.5 m before 2026-10-04).
    shoreArm_e_m: 0.1,
    shoreD_m: 0.35,
    shoreL_m: 6.5,
    bed1Arm_e_m: 0.0,
    bed1D_m: 0.35,
    bed1L_m: 8.0,
    bed1Stickup_m: 1.0,
    bed2D_m: 0.70,
    bed2L_m: 9.0,
    anchorType: 'danforth',
    weight_t: 1.5,
    holdingCoef: 8.0,
    frictionCoef: 0.35,
    concreteDensity: 2400.0
  },
  criteria: {
    sfLineIntact: 3.0,
    sfLineDamaged: 2.0,
    sfAnchorIntact: 1.5,
    sfAnchorDamaged: 1.1,
    sfPileLateral: 1.0,
    sfPileUplift: 1.0,
    sfPileSection: 1.0,
    maxLineSpacing_m: 15.0,
    minScopeRatio: 5.0,
    maxOffset_m: 1.0
  },
  attachments: [
    {
      id: 'doc_huoi_vanh_dxf',
      name: 'HỒ HUỔI VANH.dxf (Bản vẽ CAD mặt bằng 9 bè, 08/10/2026)',
      mime: 'application/dxf',
      size: 9317396,
      kind: 'dxf' as const,
      remoteUrl: 'docs_huoi_vanh/ho_huoi_vanh.dxf'
    },
    {
      id: 'doc_huoi_vanh_pdf',
      name: 'HOHUOIVANH.BỐ TRÍ BÈ PIN.pdf (9 bè, 18.354 tấm pin, 26 inverter)',
      mime: 'application/pdf',
      size: 977579,
      kind: 'pdf' as const,
      remoteUrl: 'docs_huoi_vanh/HOHUOIVANH_Bo_tri_be_pin.pdf'
    },
    {
      id: 'doc_huoi_vanh_xlsx',
      name: 'BANG_TINH_NEO_DE_VIT_XOAN.xlsx (gồm sheet 6.DE_NEO_VIT)',
      mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      size: 638109,
      kind: 'other' as const,
      remoteUrl: 'docs_huoi_vanh/BANG_TINH_NEO_DE_VIT_XOAN.xlsx'
    },
    {
      id: 'doc_huoi_vanh_screw_img',
      name: 'NEO ĐẾ VÍT XOẮN.png (Sơ đồ đế BTCT + 4 vít xoắn)',
      mime: 'image/png',
      size: 46767,
      kind: 'image' as const,
      remoteUrl: 'docs_huoi_vanh/NEO_DE_VIT_XOAN.png'
    },
    {
      id: 'doc_huoi_vanh_img',
      name: 'ANH1.jpg (Ảnh phối cảnh vệ tinh hồ Huổi Vanh)',
      mime: 'image/jpeg',
      size: 1193488,
      kind: 'image' as const,
      remoteUrl: 'docs_huoi_vanh/ANH1_web.jpg'
    },
    {
      id: 'doc_huoi_vanh_docx',
      name: 'THUYET_MINH_TINH_TOAN_KET_QUA_VA_KIEM_TRA_NEO_BE.docx (Thuyết minh phương pháp tính & kiểm tra)',
      mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      size: 15955,
      kind: 'other' as const,
      remoteUrl: 'docs_huoi_vanh/THUYET_MINH_TINH_TOAN_KET_QUA_VA_KIEM_TRA_NEO_BE.docx'
    }
  ],
  raftsSummary: HUOI_VANH_RAFTS
};
